# Generated by Django 5.0.14 on 2026-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_resena_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina_web',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
