# Generated by Django 5.0.14 on 2026-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_solicitudempleado_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rif',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
