# Generated by Django 5.0.14 on 2026-09-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_empresa_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='residencia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Residencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
