# Generated by Django 5.0.14 on 2026-09-15 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_customuser_latitud_customuser_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PEDIDO', 'Pedido'), ('PRODUCTO', 'Producto')], max_length=20),
        ),
    ]
