# Generated by Django 5.0.14 on 2026-09-16 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_producto_creado_por_producto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.OneToOneField(limit_choices_to={'role': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='token_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Token de acceso empresarial',
                'verbose_name_plural': 'Tokens de acceso empresarial',
                'ordering': ['-created'],
            },
        ),
    ]
