# Generated by Django 5.0.14 on 2026-09-17 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_tokenempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='inventario.producto'),
        ),
    ]
